from setuptools import setup, find_packages

setup(
    name="task-aware-sam-lora",
    version="0.1.0",
    description="A hypernetwork that generates task-specific LoRA adapters for SAM's mask decoder",
    author="Yash Thube",
    author_email="thubeyash09@gmail.com",
    packages=find_packages(),
    install_requires=[
        "torch>=1.12.0",
        "torchvision>=0.13.0",
        "transformers>=4.21.0",
        "segment-anything>=1.0",
        "opencv-python>=4.6.0",
        "matplotlib>=3.5.0",
        "numpy>=1.21.0",
        "pillow>=9.0.0",
        "tqdm>=4.64.0",
        "wandb>=0.13.0",
        "scikit-learn>=1.1.0",
        "pycocotools>=2.0.6",
        "albumentations>=1.3.0",
        "einops>=0.6.0",
        "timm>=0.6.0",
        "jupyter>=1.0.0",
        "ipywidgets>=7.7.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)